name: Deploy Laravel to cPanel via SSH/SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # PHP Setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer

      # Composer Setup
      - name: Install Composer Packages
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # Node Setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # NPM Setup
      - name: Install Packages
        run: npm ci

      # Build Assets
      - name: Build Assets
        run: npm run build

      
     # Sync files using SSH/rsync Action
      - name: Deploy files via SSH
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzc --delete"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: 22  # Change to 21098 if cPanel uses non-standard SSH port
          TARGET: /home/questio/public_html/Question
          EXCLUDE: "/.git/, /.github/, /node_modules/, /tests/"