name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer

      # Composer
      - name: Install Composer Packages
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # NPM
      - name: Install Packages
        run: npm ci

      # Build Vite
      - name: Build Assets
        run: npm run build

      # Install lftp
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # Upload Laravel Project
    - name: Check FTP secrets
  run: |
    if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
      echo "FTP_USERNAME is EMPTY"
    else
      echo "FTP_USERNAME is available"
    fi

    if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
      echo "FTP_PASSWORD is EMPTY"
    else
      echo "FTP_PASSWORD is available"
    fi

    if [ -z "${{ secrets.FTP_SERVER }}" ]; then
      echo "FTP_SERVER is EMPTY"
    else
      echo "FTP_SERVER is available"
    fi
          bye
          EOF
