name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer

      # Composer
      - name: Install Composer Packages
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # NPM
      - name: Install Packages
        run: npm ci

      # Build Vite
      - name: Build Assets
        run: npm run build

      # Install lftp
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # Check FTP Secrets
      - name: Check FTP secrets
        run: |
          if [ -z "${{ secrets.USERNAME }}" ]; then
            echo "USERNAME is EMPTY"
          else
            echo "USERNAME is available"
          fi

          if [ -z "${{ secrets.PASSWORD }}" ]; then
            echo "PASSWORD is EMPTY"
          else
            echo "PASSWORD is available"
          fi

          if [ -z "${{ secrets.SERVER }}" ]; then
            echo "SERVER is EMPTY"
          else
            echo "SERVER is available"
          fi

      # Test FTP Connection
           # Test FTP Connection
      - name: Test FTP Connection
        run: |
          timeout 30 lftp -d -u "${{ secrets.USERNAME }},${{ secrets.PASSWORD }}" "${{ secrets.SERVER }}" <<EOF
          set ssl:verify-certificate no
          set ftp:prefer-epsv true
          set net:timeout 10
          set net:max-retries 4
          set net:reconnect-interval-base 2
          pwd
          ls
          bye
          EOF
